<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>indexTombolRegister</name>
   <tag></tag>
   <elementGuidId>da4c3eae-329c-411d-a0a8-5959d54ee97b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a > #login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='login'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>521e41da-80a0-404f-8d73-29e3b3e9f33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2b4dd212-78e0-4f61-8e1b-2fae7860d69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary loginbutton</value>
      <webElementGuid>ca4d225f-f5fb-4baf-adbd-cc0ddf37eb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>fd943e84-7b24-4f57-bd9c-1e5db1fb80c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>af2efdb5-cc3f-4dff-9b0e-3ad5337982ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-example-navbar-collapse-1&quot;)/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[3]/a[1]/button[@id=&quot;login&quot;]</value>
      <webElementGuid>75c98747-18e2-4984-8b20-56d077762396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='login'])[3]</value>
      <webElementGuid>54e78ab5-a964-4d93-aebf-f30837958251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-example-navbar-collapse-1']/ul[2]/li[3]/a/button</value>
      <webElementGuid>f5256008-791d-492a-8b9d-f7964821a59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/button</value>
      <webElementGuid>f2ad6a94-da3f-4efb-9b56-2cf11f076fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'login' and (text() = 'register' or . = 'register')]</value>
      <webElementGuid>9d6f6e5d-ed23-43d6-bc4b-07230e0703e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
