<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alertMessageDidNotMatch</name>
   <tag></tag>
   <elementGuidId>73a00e1e-4bf6-47bf-92c9-533338de250e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='reason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97b4f023-edad-431c-a877-de2d2acdef8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>fda995de-0007-4a1d-ac11-5e862d4f33cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username/Password did not match</value>
      <webElementGuid>8ac42b6b-2aa3-45b1-a676-4775b31cf36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reason&quot;)</value>
      <webElementGuid>824815c1-784e-42f5-b4d4-1fafba12b8eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='reason']</value>
      <webElementGuid>c345d260-f4c5-484a-a103-89d2bbf774fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-alert']/span</value>
      <webElementGuid>5c3e3051-0a3a-4f25-8d6d-5917af6dc6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>347d2a96-e8a1-4fe6-854d-d3eecdf65218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'reason' and (text() = 'Username/Password did not match' or . = 'Username/Password did not match')]</value>
      <webElementGuid>dcd835ac-d5dc-4105-8dc5-566c01eeb5ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
